const ACCEPTED_COLOUR = 0xFEE75D;
const REJECTED_COLOUR = 0xED4245;
const UNBANNED_COLOUR = 0xFEE75C;
const COMPLETED_COLOUR = 0x3BA55D

export { ACCEPTED_COLOUR, REJECTED_COLOUR, UNBANNED_COLOUR, COMPLETED_COLOUR };